In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

print("DeliveryRisk Engine - Data Understanding")

DeliveryRisk Engine - Data Understanding

In [2]:
from pathlib import Path

DATA_DIR = Path("../data/raw")

customers = pd.read_csv(DATA_DIR / "olist_customers_dataset.csv")
geolocation = pd.read_csv(DATA_DIR / "olist_geolocation_dataset.csv")
order_items = pd.read_csv(DATA_DIR / "olist_order_items_dataset.csv")
payments = pd.read_csv(DATA_DIR / "olist_order_payments_dataset.csv")
reviews = pd.read_csv(DATA_DIR / "olist_order_reviews_dataset.csv")
orders = pd.read_csv(DATA_DIR / "olist_orders_dataset.csv")
products = pd.read_csv(DATA_DIR / "olist_products_dataset.csv")
sellers = pd.read_csv(DATA_DIR / "olist_sellers_dataset.csv")
category_translation = pd.read_csv(
    DATA_DIR / "product_category_name_translation.csv"
)

print("All datasets loaded successfully.")

All datasets loaded successfully.

In [ ]:
datasets = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "orders": orders,
    "products": products,
    "sellers": sellers,
    "category_translation": category_translation
}

for name, df in datasets.items():
    print(f"{name:22} {df.shape}")

customers              (99441, 5)
geolocation            (1000163, 5)
order_items            (112650, 7)
payments               (103886, 5)
reviews                (99224, 7)
orders                 (99441, 8)
products               (32951, 9)
sellers                (3095, 4)
category_translation   (71, 2)

In [4]:
orders.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date']

In [5]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [6]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [7]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [8]:
orders["order_status"].value_counts(dropna=False)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [9]:
orders[
    [
        "order_id",
        "order_status",
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
].head(10)

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,136cce7faa42fdb2cefd53fdc79a6098,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
7,6514b8ad8028c9f2cc2374ded245783f,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
8,76c6e866289321a7c93b82b54852dc33,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
9,e69bfb5eb88e0ed6a785585b27e16dbf,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00

In [10]:
timestamp_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in timestamp_cols:
    orders[col] = pd.to_datetime(orders[col])

orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [11]:
delivered_orders = orders[
    orders["order_status"] == "delivered"
].copy()

print("Delivered orders:", len(delivered_orders))

Delivered orders: 96478

In [12]:
delivered_orders["late_delivery"] = (
    delivered_orders["order_delivered_customer_date"]
    > delivered_orders["order_estimated_delivery_date"]
).astype(int)

In [13]:
delivered_orders["late_delivery"].value_counts()

late_delivery
0    88652
1     7826
Name: count, dtype: int64

In [14]:
delivered_orders["late_delivery"].value_counts(normalize=True) * 100

late_delivery
0    91.888306
1     8.111694
Name: proportion, dtype: float64

In [15]:
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)
    for col in df.columns:
        print(col)

============================================================
CUSTOMERS
============================================================
customer_id
customer_unique_id
customer_zip_code_prefix
customer_city
customer_state

============================================================
GEOLOCATION
============================================================
geolocation_zip_code_prefix
geolocation_lat
geolocation_lng
geolocation_city
geolocation_state

============================================================
ORDER_ITEMS
============================================================
order_id
order_item_id
product_id
seller_id
shipping_limit_date
price
freight_value

============================================================
PAYMENTS
============================================================
order_id
payment_sequential
payment_type
payment_installments
payment_value

============================================================
REVIEWS
============================================================
review_id
order_id
review_score
review_comment_title
review_comment_message
review_creation_date
review_answer_timestamp

============================================================
ORDERS
============================================================
order_id
customer_id
order_status
order_purchase_timestamp
order_approved_at
order_delivered_carrier_date
order_delivered_customer_date
order_estimated_delivery_date

============================================================
PRODUCTS
============================================================
product_id
product_category_name
product_name_lenght
product_description_lenght
product_photos_qty
product_weight_g
product_length_cm
product_height_cm
product_width_cm

============================================================
SELLERS
============================================================
seller_id
seller_zip_code_prefix
seller_city
seller_state

============================================================
CATEGORY_TRANSLATION
============================================================
product_category_name
product_category_name_english

In [16]:
customers.columns.tolist()

['customer_id',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state']

In [17]:
order_items.columns.tolist()

['order_id',
 'order_item_id',
 'product_id',
 'seller_id',
 'shipping_limit_date',
 'price',
 'freight_value']

In [18]:
products.columns.tolist()

['product_id',
 'product_category_name',
 'product_name_lenght',
 'product_description_lenght',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm']

In [19]:
sellers.columns.tolist()

['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

In [20]:
geolocation.columns.tolist()

['geolocation_zip_code_prefix',
 'geolocation_lat',
 'geolocation_lng',
 'geolocation_city',
 'geolocation_state']

In [21]:
order_base = delivered_orders[
    [
        "order_id",
        "customer_id",
        "order_purchase_timestamp",
        "order_estimated_delivery_date",
        "late_delivery"
    ]
].copy()

order_base.head()

,order_id,customer_id,order_purchase_timestamp,order_estimated_delivery_date,late_delivery
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,2017-10-18,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,2018-08-13,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49,2018-09-04,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06,2017-12-15,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13 21:18:39,2018-02-26,0

In [22]:
order_base = order_base.merge(
    customers[
        [
            "customer_id",
            "customer_unique_id",
            "customer_zip_code_prefix",
            "customer_city",
            "customer_state"
        ]
    ],
    on="customer_id",
    how="left"
)

order_base.head()

,order_id,customer_id,order_purchase_timestamp,order_estimated_delivery_date,late_delivery,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,2017-10-18,0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,2018-08-13,0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49,2018-09-04,0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06,2017-12-15,0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13 21:18:39,2018-02-26,0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [23]:
print("Rows:", len(order_base))
print("Unique orders:", order_base["order_id"].nunique())

Rows: 96478
Unique orders: 96478

In [24]:
item_features = (
    order_items
    .groupby("order_id")
    .agg(
        item_count=("order_item_id", "count"),
        total_price=("price", "sum"),
        total_freight=("freight_value", "sum"),
        avg_item_price=("price", "mean"),
        unique_products=("product_id", "nunique"),
        unique_sellers=("seller_id", "nunique")
    )
    .reset_index()
)

item_features.head()

,order_id,item_count,total_price,total_freight,avg_item_price,unique_products,unique_sellers
0,00010242fe8c5a6d1ba2dd792cb16214,1,58.90,13.29,58.90,1,1
1,00018f77f2f0320c557190d7a144bdd3,1,239.90,19.93,239.90,1,1
2,000229ec398224ef6ca0657da4fc703e,1,199.00,17.87,199.00,1,1
3,00024acbcdf0a6daa1e931b038114c75,1,12.99,12.79,12.99,1,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,199.90,18.14,199.90,1,1

In [25]:
order_base = order_base.merge(
    item_features,
    on="order_id",
    how="left"
)

print(order_base.shape)

(96478, 15)

In [26]:
order_base.head()

,order_id,customer_id,order_purchase_timestamp,order_estimated_delivery_date,late_delivery,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,item_count,total_price,total_freight,avg_item_price,unique_products,unique_sellers
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,2017-10-18,0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1,29.99,8.72,29.99,1,1
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,2018-08-13,0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1,118.70,22.76,118.70,1,1
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49,2018-09-04,0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1,159.90,19.22,159.90,1,1
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06,2017-12-15,0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1,45.00,27.20,45.00,1,1
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13 21:18:39,2018-02-26,0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1,19.90,8.72,19.90,1,1

In [27]:
print("PRODUCT COLUMNS")
print(products.columns.tolist())

print("\nSELLER COLUMNS")
print(sellers.columns.tolist())

PRODUCT COLUMNS
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

SELLER COLUMNS
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

In [28]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [29]:
sellers.head()

                          seller_id  seller_zip_code_prefix        seller_city seller_state
0  3442f8959a84dea7ee197c632cb2df15                   13023           campinas           SP
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844         mogi guacu           SP
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031     rio de janeiro           RJ
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195          sao paulo           SP
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914  braganca paulista           SP

In [31]:
order_product_data = order_items.merge(
    products[
        [
            "product_id",
            "product_category_name",
            "product_name_lenght",
            "product_description_lenght",
            "product_photos_qty",
            "product_weight_g",
            "product_length_cm",
            "product_height_cm",
            "product_width_cm"
        ]
    ],
    on="product_id",
    how="left"
)

order_product_data.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,cool_stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,pet_shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,moveis_decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,ferramentas_jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0

In [32]:
product_features = (
    order_product_data
    .groupby("order_id")
    .agg(
        product_count=("product_id", "count"),
        unique_product_count=("product_id", "nunique"),
        unique_category_count=("product_category_name", "nunique"),
        avg_product_name_length=("product_name_lenght", "mean"),
        avg_description_length=("product_description_lenght", "mean"),
        avg_product_photos=("product_photos_qty", "mean"),
        total_product_weight_g=("product_weight_g", "sum"),
        avg_product_weight_g=("product_weight_g", "mean"),
        avg_product_length_cm=("product_length_cm", "mean"),
        avg_product_height_cm=("product_height_cm", "mean"),
        avg_product_width_cm=("product_width_cm", "mean")
    )
    .reset_index()
)

product_features.head()

,order_id,product_count,unique_product_count,unique_category_count,avg_product_name_length,avg_description_length,avg_product_photos,total_product_weight_g,avg_product_weight_g,avg_product_length_cm,avg_product_height_cm,avg_product_width_cm
0,00010242fe8c5a6d1ba2dd792cb16214,1,1,1,58.0,598.0,4.0,650.0,650.0,28.0,9.0,14.0
1,00018f77f2f0320c557190d7a144bdd3,1,1,1,56.0,239.0,2.0,30000.0,30000.0,50.0,30.0,40.0
2,000229ec398224ef6ca0657da4fc703e,1,1,1,59.0,695.0,2.0,3050.0,3050.0,33.0,13.0,33.0
3,00024acbcdf0a6daa1e931b038114c75,1,1,1,42.0,480.0,1.0,200.0,200.0,16.0,10.0,15.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,1,1,59.0,409.0,1.0,3750.0,3750.0,35.0,40.0,30.0

In [33]:
print("Product feature rows:", len(product_features))
print("Unique orders:", product_features["order_id"].nunique())

Product feature rows: 98666
Unique orders: 98666

In [34]:
order_base = order_base.merge(
    product_features,
    on="order_id",
    how="left"
)

print("Shape:", order_base.shape)
print("Unique orders:", order_base["order_id"].nunique())

Shape: (96478, 26)
Unique orders: 96478

In [36]:
order_seller_data = order_items.merge(
    sellers[
        [
            "seller_id",
            "seller_zip_code_prefix",
            "seller_city",
            "seller_state"
        ]
    ],
    on="seller_id",
    how="left"
)

order_seller_data.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,seller_zip_code_prefix,seller_city,seller_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,27277,volta redonda,SP
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,3471,sao paulo,SP
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,37564,borda da mata,MG
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,14403,franca,SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,87900,loanda,PR

In [37]:
seller_features = (
    order_seller_data
    .groupby("order_id")
    .agg(
        unique_seller_count=("seller_id", "nunique"),
        unique_seller_states=("seller_state", "nunique"),
        seller_state_mode=(
            "seller_state",
            lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan
        ),
        avg_seller_zip=("seller_zip_code_prefix", "mean")
    )
    .reset_index()
)

seller_features.head()

                           order_id  unique_seller_count  unique_seller_states seller_state_mode  avg_seller_zip
0  00010242fe8c5a6d1ba2dd792cb16214                    1                     1                SP         27277.0
1  00018f77f2f0320c557190d7a144bdd3                    1                     1                SP          3471.0
2  000229ec398224ef6ca0657da4fc703e                    1                     1                MG         37564.0
3  00024acbcdf0a6daa1e931b038114c75                    1                     1                SP         14403.0
4  00042b26cf59d7ce69dfabb4e55b4fd9                    1                     1                PR         87900.0

In [38]:
print("Seller feature rows:", len(seller_features))
print("Unique orders:", seller_features["order_id"].nunique())

Seller feature rows: 98666
Unique orders: 98666

In [39]:
order_base = order_base.merge(
    seller_features,
    on="order_id",
    how="left"
)

print("Shape:", order_base.shape)
print("Unique orders:", order_base["order_id"].nunique())

Shape: (96478, 30)
Unique orders: 96478

In [40]:
order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"]
)

shipping_features = (
    order_items
    .merge(
        orders[["order_id", "order_purchase_timestamp"]],
        on="order_id",
        how="left"
    )
)

shipping_features["order_purchase_timestamp"] = pd.to_datetime(
    shipping_features["order_purchase_timestamp"]
)

shipping_features["shipping_window_hours"] = (
    shipping_features["shipping_limit_date"]
    - shipping_features["order_purchase_timestamp"]
).dt.total_seconds() / 3600

shipping_features = (
    shipping_features
    .groupby("order_id")
    .agg(
        avg_shipping_window_hours=("shipping_window_hours", "mean"),
        min_shipping_window_hours=("shipping_window_hours", "min")
    )
    .reset_index()
)

shipping_features.head()

                           order_id  avg_shipping_window_hours  min_shipping_window_hours
0  00010242fe8c5a6d1ba2dd792cb16214                 144.775833                 144.775833
1  00018f77f2f0320c557190d7a144bdd3                 168.201944                 168.201944
2  000229ec398224ef6ca0657da4fc703e                  96.249722                  96.249722
3  00024acbcdf0a6daa1e931b038114c75                 168.161944                 168.161944
4  00042b26cf59d7ce69dfabb4e55b4fd9                 216.000000                 216.000000

In [41]:
print("Shipping feature rows:", len(shipping_features))
print("Unique orders:", shipping_features["order_id"].nunique())

Shipping feature rows: 98666
Unique orders: 98666

In [42]:
order_base = order_base.merge(
    shipping_features,
    on="order_id",
    how="left"
)

print("Shape:", order_base.shape)
print("Unique orders:", order_base["order_id"].nunique())

Shape: (96478, 32)
Unique orders: 96478

In [43]:
order_base["purchase_hour"] = (
    order_base["order_purchase_timestamp"].dt.hour
)

order_base["purchase_dayofweek"] = (
    order_base["order_purchase_timestamp"].dt.dayofweek
)

order_base["purchase_month"] = (
    order_base["order_purchase_timestamp"].dt.month
)

order_base["purchase_day"] = (
    order_base["order_purchase_timestamp"].dt.day
)

order_base[
    [
        "order_purchase_timestamp",
        "purchase_hour",
        "purchase_dayofweek",
        "purchase_month",
        "purchase_day"
    ]
].head()

  order_purchase_timestamp  purchase_hour  purchase_dayofweek  purchase_month  purchase_day
0      2017-10-02 10:56:33             10                   0              10             2
1      2018-07-24 20:41:37             20                   1               7            24
2      2018-08-08 08:38:49              8                   2               8             8
3      2017-11-18 19:28:06             19                   5              11            18
4      2018-02-13 21:18:39             21                   1               2            13

In [44]:
geo_lookup = (
    geolocation
    .groupby("geolocation_zip_code_prefix")
    .agg(
        latitude=("geolocation_lat", "mean"),
        longitude=("geolocation_lng", "mean")
    )
    .reset_index()
)

geo_lookup.head()

   geolocation_zip_code_prefix   latitude  longitude
0                         1001 -23.550190 -46.634024
1                         1002 -23.548146 -46.634979
2                         1003 -23.548994 -46.635731
3                         1004 -23.549799 -46.634757
4                         1005 -23.549456 -46.636733

In [45]:
print("Unique ZIP prefixes:", len(geo_lookup))

Unique ZIP prefixes: 19015

In [46]:
geo_orders = (
    order_items[
        ["order_id", "seller_id"]
    ]
    .merge(
        order_base[
            [
                "order_id",
                "customer_zip_code_prefix"
            ]
        ],
        on="order_id",
        how="left"
    )
    .merge(
        sellers[
            [
                "seller_id",
                "seller_zip_code_prefix"
            ]
        ],
        on="seller_id",
        how="left"
    )
)

geo_orders.head()

,order_id,seller_id,customer_zip_code_prefix,seller_zip_code_prefix
0,00010242fe8c5a6d1ba2dd792cb16214,48436dade18ac8b2bce089ec2a041202,28013.0,27277
1,00018f77f2f0320c557190d7a144bdd3,dd7ddc04e1b6c2c614352b383efe2d36,15775.0,3471
2,000229ec398224ef6ca0657da4fc703e,5b51032eddd242adc84c38acab88f23d,35661.0,37564
3,00024acbcdf0a6daa1e931b038114c75,9d7a1d34a5052409006425275ba1c2b4,12952.0,14403
4,00042b26cf59d7ce69dfabb4e55b4fd9,df560393f3a51e74553ab94004ba5c87,13226.0,87900

In [47]:
geo_orders = geo_orders.merge(
    geo_lookup,
    left_on="customer_zip_code_prefix",
    right_on="geolocation_zip_code_prefix",
    how="left"
)

geo_orders = geo_orders.rename(
    columns={
        "latitude": "customer_lat",
        "longitude": "customer_lng"
    }
)

geo_orders = geo_orders.drop(
    columns=["geolocation_zip_code_prefix"]
)

geo_orders = geo_orders.merge(
    geo_lookup,
    left_on="seller_zip_code_prefix",
    right_on="geolocation_zip_code_prefix",
    how="left"
)

geo_orders = geo_orders.rename(
    columns={
        "latitude": "seller_lat",
        "longitude": "seller_lng"
    }
)

geo_orders = geo_orders.drop(
    columns=["geolocation_zip_code_prefix"]
)

geo_orders.head()

,order_id,seller_id,customer_zip_code_prefix,seller_zip_code_prefix,customer_lat,customer_lng,seller_lat,seller_lng
0,00010242fe8c5a6d1ba2dd792cb16214,48436dade18ac8b2bce089ec2a041202,28013.0,27277,-21.762775,-41.309633,-22.496953,-44.127492
1,00018f77f2f0320c557190d7a144bdd3,dd7ddc04e1b6c2c614352b383efe2d36,15775.0,3471,-20.220527,-50.903424,-23.565096,-46.518565
2,000229ec398224ef6ca0657da4fc703e,5b51032eddd242adc84c38acab88f23d,35661.0,37564,-19.870305,-44.593326,-22.262584,-46.171124
3,00024acbcdf0a6daa1e931b038114c75,9d7a1d34a5052409006425275ba1c2b4,12952.0,14403,-23.089925,-46.611654,-20.553624,-47.387359
4,00042b26cf59d7ce69dfabb4e55b4fd9,df560393f3a51e74553ab94004ba5c87,13226.0,87900,-23.243402,-46.827614,-22.929384,-53.135873

In [48]:
from numpy import radians, sin, cos, sqrt, arctan2

lat1 = radians(geo_orders["customer_lat"])
lon1 = radians(geo_orders["customer_lng"])
lat2 = radians(geo_orders["seller_lat"])
lon2 = radians(geo_orders["seller_lng"])

dlat = lat2 - lat1
dlon = lon2 - lon1

a = (
    sin(dlat / 2) ** 2
    + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
)

geo_orders["seller_customer_distance_km"] = (
    2 * 6371 * arctan2(sqrt(a), sqrt(1 - a))
)

geo_orders[
    ["order_id", "seller_customer_distance_km"]
].head()

                           order_id  seller_customer_distance_km
0  00010242fe8c5a6d1ba2dd792cb16214                   301.504681
1  00018f77f2f0320c557190d7a144bdd3                   585.563937
2  000229ec398224ef6ca0657da4fc703e                   312.343511
3  00024acbcdf0a6daa1e931b038114c75                   293.168420
4  00042b26cf59d7ce69dfabb4e55b4fd9                   646.163463

In [49]:
geo_features = (
    geo_orders
    .groupby("order_id")
    .agg(
        avg_seller_customer_distance_km=(
            "seller_customer_distance_km",
            "mean"
        ),
        min_seller_customer_distance_km=(
            "seller_customer_distance_km",
            "min"
        ),
        max_seller_customer_distance_km=(
            "seller_customer_distance_km",
            "max"
        )
    )
    .reset_index()
)

geo_features.head()

,order_id,avg_seller_customer_distance_km,min_seller_customer_distance_km,max_seller_customer_distance_km
0,00010242fe8c5a6d1ba2dd792cb16214,301.504681,301.504681,301.504681
1,00018f77f2f0320c557190d7a144bdd3,585.563937,585.563937,585.563937
2,000229ec398224ef6ca0657da4fc703e,312.343511,312.343511,312.343511
3,00024acbcdf0a6daa1e931b038114c75,293.168420,293.168420,293.168420
4,00042b26cf59d7ce69dfabb4e55b4fd9,646.163463,646.163463,646.163463

In [50]:
print("Geography feature rows:", len(geo_features))
print("Unique orders:", geo_features["order_id"].nunique())

Geography feature rows: 98666
Unique orders: 98666

In [51]:
geo_features.describe().T

                                   count        mean         std  min         25%         50%         75%          max
avg_seller_customer_distance_km  96002.0  600.761263  593.438763  0.0  187.704651  433.854409  797.667364  8677.911622
min_seller_customer_distance_km  96002.0  599.436177  593.520098  0.0  182.899976  431.895429  796.910869  8677.911622
max_seller_customer_distance_km  96002.0  602.097242  593.914993  0.0  189.298555  435.610203  800.279812  8677.911622

In [52]:
order_base = order_base.merge(
    geo_features,
    on="order_id",
    how="left"
)

print("Shape:", order_base.shape)
print("Unique orders:", order_base["order_id"].nunique())

Shape: (96478, 39)
Unique orders: 96478

In [53]:
geo_orders_unique = (
    geo_orders[
        [
            "order_id",
            "seller_id",
            "seller_customer_distance_km"
        ]
    ]
    .drop_duplicates()
)

print("Order-seller pairs:", len(geo_orders_unique))
print(
    "Unique order-seller pairs:",
    geo_orders_unique[["order_id", "seller_id"]].drop_duplicates().shape[0]
)

Order-seller pairs: 100010
Unique order-seller pairs: 100010

In [54]:
geo_features = (
    geo_orders_unique
    .groupby("order_id")
    .agg(
        avg_seller_customer_distance_km=(
            "seller_customer_distance_km",
            "mean"
        ),
        min_seller_customer_distance_km=(
            "seller_customer_distance_km",
            "min"
        ),
        max_seller_customer_distance_km=(
            "seller_customer_distance_km",
            "max"
        )
    )
    .reset_index()
)

geo_features.head()

,order_id,avg_seller_customer_distance_km,min_seller_customer_distance_km,max_seller_customer_distance_km
0,00010242fe8c5a6d1ba2dd792cb16214,301.504681,301.504681,301.504681
1,00018f77f2f0320c557190d7a144bdd3,585.563937,585.563937,585.563937
2,000229ec398224ef6ca0657da4fc703e,312.343511,312.343511,312.343511
3,00024acbcdf0a6daa1e931b038114c75,293.168420,293.168420,293.168420
4,00042b26cf59d7ce69dfabb4e55b4fd9,646.163463,646.163463,646.163463

In [55]:
print(
    "Orders without distance:",
    geo_features["avg_seller_customer_distance_km"].isna().sum()
)

print(
    "Percentage without distance:",
    geo_features["avg_seller_customer_distance_km"].isna().mean() * 100
)

Orders without distance: 2664
Percentage without distance: 2.700018243366509

In [56]:
geo_features["avg_seller_customer_distance_km"].describe()

count    96002.000000
mean       600.763948
std        593.419151
min          0.000000
25%        187.779725
50%        433.878565
75%        797.665556
max       8677.911622
Name: avg_seller_customer_distance_km, dtype: float64

In [57]:
order_base = order_base.merge(
    geo_features,
    on="order_id",
    how="left"
)

print("Shape:", order_base.shape)
print("Unique orders:", order_base["order_id"].nunique())

Shape: (96478, 42)
Unique orders: 96478

In [58]:
order_base = order_base.sort_values(
    "order_purchase_timestamp"
).reset_index(drop=True)

print(
    order_base[
        [
            "order_id",
            "order_purchase_timestamp",
            "customer_unique_id",
            "late_delivery"
        ]
    ].head()
)

                           order_id order_purchase_timestamp                customer_unique_id  late_delivery
0  bfbd0f9bdef84302105ad712db648a6c      2016-09-15 12:16:38  830d5b7aaa3b6f1e9ad63703bec97d23              1
1  3b697a20d9e427646d92567910af6d57      2016-10-03 09:44:50  32ea3bdedab835c3aa6cb68ce66565ef              0
2  be5bc2f0da14d8071e2d45451ad119d9      2016-10-03 16:56:50  2f64e403852e6893ae37485d5fcacdaf              0
3  a41c8759fbe7aab36ea07e038b2d4465      2016-10-03 21:13:36  61db744d2f835035a5625b59350c6b63              0
4  d207cc272675637bfed0062edffd0818      2016-10-03 22:06:03  8d3a54507421dbd2ce0a1d58046826e0              0

In [59]:
order_sellers = (
    order_items[
        ["order_id", "seller_id"]
    ]
    .drop_duplicates()
)

order_sellers = order_sellers.merge(
    order_base[
        [
            "order_id",
            "order_purchase_timestamp",
            "late_delivery"
        ]
    ],
    on="order_id",
    how="inner"
)

print("Order-seller pairs:", len(order_sellers))
order_sellers.head()

Order-seller pairs: 97819

                           order_id                         seller_id order_purchase_timestamp  late_delivery
0  00010242fe8c5a6d1ba2dd792cb16214  48436dade18ac8b2bce089ec2a041202      2017-09-13 08:59:02              0
1  00018f77f2f0320c557190d7a144bdd3  dd7ddc04e1b6c2c614352b383efe2d36      2017-04-26 10:53:06              0
2  000229ec398224ef6ca0657da4fc703e  5b51032eddd242adc84c38acab88f23d      2018-01-14 14:33:31              0
3  00024acbcdf0a6daa1e931b038114c75  9d7a1d34a5052409006425275ba1c2b4      2018-08-08 10:00:35              0
4  00042b26cf59d7ce69dfabb4e55b4fd9  df560393f3a51e74553ab94004ba5c87      2017-02-04 13:57:51              0

In [60]:
order_sellers = order_sellers.sort_values(
    ["seller_id", "order_purchase_timestamp"]
)

order_sellers["seller_previous_orders"] = (
    order_sellers
    .groupby("seller_id")
    .cumcount()
)

order_sellers["seller_previous_lates"] = (
    order_sellers
    .groupby("seller_id")["late_delivery"]
    .cumsum()
    .shift(1)
    .fillna(0)
)

In [61]:
order_sellers["seller_historical_late_rate"] = np.where(
    order_sellers["seller_previous_orders"] > 0,
    order_sellers["seller_previous_lates"]
    / order_sellers["seller_previous_orders"],
    np.nan
)

In [62]:
order_sellers[
    [
        "seller_id",
        "order_purchase_timestamp",
        "late_delivery",
        "seller_previous_orders",
        "seller_previous_lates",
        "seller_historical_late_rate"
    ]
].head(20)

,seller_id,order_purchase_timestamp,late_delivery,seller_previous_orders,seller_previous_lates,seller_historical_late_rate
81331,0015a82c2db000af6aaaf3ae2ecb0532,2017-09-26 22:17:05,0,0,0.0,NaN
59942,0015a82c2db000af6aaaf3ae2ecb0532,2017-10-12 13:33:22,0,1,0.0,0.000000
48535,0015a82c2db000af6aaaf3ae2ecb0532,2017-10-18 08:16:34,0,2,0.0,0.000000
23038,001cca7ae9ae17fb1caed9dfb1094831,2017-02-04 19:06:04,0,0,0.0,NaN
89898,001cca7ae9ae17fb1caed9dfb1094831,2017-02-18 23:26:24,0,1,0.0,0.000000
39315,001cca7ae9ae17fb1caed9dfb1094831,2017-02-23 11:42:38,0,2,0.0,0.000000
77237,001cca7ae9ae17fb1caed9dfb1094831,2017-02-27 16:23:21,0,3,0.0,0.000000
36867,001cca7ae9ae17fb1caed9dfb1094831,2017-02-27 23:54:11,0,4,0.0,0.000000
66519,001cca7ae9ae17fb1caed9dfb1094831,2017-03-02 16:12:33,0,5,0.0,0.000000
52688,001cca7ae9ae17fb1caed9dfb1094831,2017-03-03 15:44:38,0,6,0.0,0.000000
49477,001cca7ae9ae17fb1caed9dfb1094831,2017-03-15 22:26:48,0,7,0.0,0.000000
25404,001cca7ae9ae17fb1caed9dfb1094831,2017-03-17 14:22:50,0,8,0.0,0.000000
13894,001cca7ae9ae17fb1caed9dfb1094831,2017-03-23 11:38:44,0,9,0.0,0.000000
33946,001cca7ae9ae17fb1caed9dfb1094831,2017-03-23 21:08:47,0,10,0.0,0.000000
35571,001cca7ae9ae17fb1caed9dfb1094831,2017-03-25 12:57:33,0,11,0.0,0.000000
56544,001cca7ae9ae17fb1caed9dfb1094831,2017-03-27 20:13:09,0,12,0.0,0.000000
89801,001cca7ae9ae17fb1caed9dfb1094831,2017-03-27 22:20:14,1,13,0.0,0.000000
75252,001cca7ae9ae17fb1caed9dfb1094831,2017-03-28 23:10:01,0,14,1.0,0.071429
42493,001cca7ae9ae17fb1caed9dfb1094831,2017-03-31 15:41:59,0,15,1.0,0.066667
19404,001cca7ae9ae17fb1caed9dfb1094831,2017-04-02 18:52:07,0,16,1.0,0.062500

In [63]:
seller_history_features = (
    order_sellers
    .groupby("order_id")
    .agg(
        avg_seller_historical_late_rate=(
            "seller_historical_late_rate",
            "mean"
        ),
        max_seller_historical_late_rate=(
            "seller_historical_late_rate",
            "max"
        ),
        avg_seller_previous_orders=(
            "seller_previous_orders",
            "mean"
        ),
        max_seller_previous_orders=(
            "seller_previous_orders",
            "max"
        )
    )
    .reset_index()
)

In [64]:
seller_history_features.head()

,order_id,avg_seller_historical_late_rate,max_seller_historical_late_rate,avg_seller_previous_orders,max_seller_previous_orders
0,00010242fe8c5a6d1ba2dd792cb16214,0.048193,0.048193,83.0,83
1,00018f77f2f0320c557190d7a144bdd3,NaN,NaN,0.0,0
2,000229ec398224ef6ca0657da4fc703e,0.000000,0.000000,6.0,6
3,00024acbcdf0a6daa1e931b038114c75,0.100000,0.100000,10.0,10
4,00042b26cf59d7ce69dfabb4e55b4fd9,0.000000,0.000000,3.0,3

In [75]:
seller_order_history = (
    order_items[
        ["order_id", "seller_id"]
    ]
    .drop_duplicates()
    .merge(
        delivered_orders[
            [
                "order_id",
                "order_purchase_timestamp",
                "order_delivered_customer_date",
                "late_delivery"
            ]
        ],
        on="order_id",
        how="inner"
    )
)

print("Seller-order pairs:", len(seller_order_history))
seller_order_history.head()

Seller-order pairs: 97819

,order_id,seller_id,order_purchase_timestamp,order_delivered_customer_date,late_delivery
0,00010242fe8c5a6d1ba2dd792cb16214,48436dade18ac8b2bce089ec2a041202,2017-09-13 08:59:02,2017-09-20 23:43:48,0
1,00018f77f2f0320c557190d7a144bdd3,dd7ddc04e1b6c2c614352b383efe2d36,2017-04-26 10:53:06,2017-05-12 16:04:24,0
2,000229ec398224ef6ca0657da4fc703e,5b51032eddd242adc84c38acab88f23d,2018-01-14 14:33:31,2018-01-22 13:19:16,0
3,00024acbcdf0a6daa1e931b038114c75,9d7a1d34a5052409006425275ba1c2b4,2018-08-08 10:00:35,2018-08-14 13:32:39,0
4,00042b26cf59d7ce69dfabb4e55b4fd9,df560393f3a51e74553ab94004ba5c87,2017-02-04 13:57:51,2017-03-01 16:42:31,0

In [80]:
seller_events = (
    seller_order_history[
        [
            "seller_id",
            "order_id",
            "order_delivered_customer_date",
            "late_delivery"
        ]
    ]
    .dropna(subset=["order_delivered_customer_date"])
    .sort_values(
        ["order_delivered_customer_date", "seller_id"]
    )
    .reset_index(drop=True)
)

seller_events["completed_orders_so_far"] = (
    seller_events
    .groupby("seller_id")
    .cumcount() + 1
)

seller_events["completed_lates_so_far"] = (
    seller_events
    .groupby("seller_id")["late_delivery"]
    .cumsum()
)

In [81]:
current_seller_orders = (
    seller_order_history[
        [
            "order_id",
            "seller_id",
            "order_purchase_timestamp"
        ]
    ]
    .sort_values(
        ["order_purchase_timestamp", "seller_id"]
    )
    .copy()
)

In [85]:
current_seller_orders = (
    seller_order_history[
        [
            "order_id",
            "seller_id",
            "order_purchase_timestamp"
        ]
    ]
    .sort_values(
        ["order_purchase_timestamp", "seller_id"]
    )
    .reset_index(drop=True)
)

current_seller_orders.head()

                           order_id                         seller_id order_purchase_timestamp
0  bfbd0f9bdef84302105ad712db648a6c  ecccfa2bb93b34a3bf033cc5d1dcdc69      2016-09-15 12:16:38
1  3b697a20d9e427646d92567910af6d57  522620dcb18a6b31cd7bdf73665113a9      2016-10-03 09:44:50
2  be5bc2f0da14d8071e2d45451ad119d9  f09b760d23495ac9a7e00d29b769007c      2016-10-03 16:56:50
3  a41c8759fbe7aab36ea07e038b2d4465  45d33f715e24d15a6ccf5c17b3a23e3c      2016-10-03 21:13:36
4  d207cc272675637bfed0062edffd0818  cca3071e3e9bb7d12640c9fbe2301306      2016-10-03 22:06:03

In [86]:
print(
    "Missing delivery dates:",
    seller_events["order_delivered_customer_date"].isna().sum()
)

print(
    "Seller events:",
    len(seller_events)
)

Missing delivery dates: 0
Seller events: 97811

In [83]:
seller_history = pd.merge_asof(
    current_seller_orders,
    seller_events[
        [
            "seller_id",
            "order_delivered_customer_date",
            "completed_orders_so_far",
            "completed_lates_so_far"
        ]
    ],
    left_on="order_purchase_timestamp",
    right_on="order_delivered_customer_date",
    by="seller_id",
    direction="backward",
    allow_exact_matches=False
)

seller_history.head(20)

,order_id,seller_id,order_purchase_timestamp,order_delivered_customer_date,completed_orders_so_far,completed_lates_so_far
0,bfbd0f9bdef84302105ad712db648a6c,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-15 12:16:38,NaT,NaN,NaN
1,3b697a20d9e427646d92567910af6d57,522620dcb18a6b31cd7bdf73665113a9,2016-10-03 09:44:50,NaT,NaN,NaN
2,be5bc2f0da14d8071e2d45451ad119d9,f09b760d23495ac9a7e00d29b769007c,2016-10-03 16:56:50,NaT,NaN,NaN
3,a41c8759fbe7aab36ea07e038b2d4465,45d33f715e24d15a6ccf5c17b3a23e3c,2016-10-03 21:13:36,NaT,NaN,NaN
4,d207cc272675637bfed0062edffd0818,cca3071e3e9bb7d12640c9fbe2301306,2016-10-03 22:06:03,NaT,NaN,NaN
5,cd3b8574c82b42fc8129f6d502690c3e,b499c00f28f4b7069ff6550af8c1348a,2016-10-03 22:31:31,NaT,NaN,NaN
6,ae8a60e4b03c5a4ba9ca0672c164b181,817f85dbb65aa3e70831d90fe75cdf89,2016-10-03 22:44:10,NaT,NaN,NaN
7,ef1b29b591d31d57c0d7337460dd83c9,cca3071e3e9bb7d12640c9fbe2301306,2016-10-03 22:51:30,NaT,NaN,NaN
8,0a0837a5eee9e7a9ce2b1fa831944d27,3481aa57cd91f9f9d3fa1fa12d9a3bf7,2016-10-04 09:06:10,NaT,NaN,NaN
9,1ff217aa612f6cd7c4255c9bfe931c8b,4b1eaadf791bdbbad8c4a35b65236d52,2016-10-04 09:16:33,NaT,NaN,NaN
10,ed8c7b1b3eb256c70ce0c74231e1da88,5b179e9e8cc7ab6fd113a46ca584da81,2016-10-04 09:59:03,NaT,NaN,NaN
11,c3d9e402b6a0fbe2a5f7fc5b41117c38,624f4ece8da4aafb77699233d480f8ef,2016-10-04 10:16:04,NaT,NaN,NaN
12,46046adea0e222a29259bad3d922fee8,99eaacc9e6046db1c82b163c5f84869f,2016-10-04 10:41:17,NaT,NaN,NaN
13,80606b26965c5ed21e85a085e0667b63,77530e9772f57a62c906e1c21538ab82,2016-10-04 11:03:14,NaT,NaN,NaN
14,79ffdd52a918bbe867895a4b183d6457,c7dcd301ecfe5ab7f778ac172cf74be7,2016-10-04 12:06:11,NaT,NaN,NaN
15,c4b41c36dd589e901f6879f25a74ec1d,ce27a3cc3c8cc1ea79d11e561e9bebb6,2016-10-04 12:53:17,NaT,NaN,NaN
16,36989eb07a0de2d3d3129eea35553875,939f6e231201f26803cb5c3a3d2940b3,2016-10-04 13:11:29,NaT,NaN,NaN
17,3f72d2b757e725cd48a4726f831c7789,620c87c171fb2a6dd6e8bb4dec959fc6,2016-10-04 13:15:46,NaT,NaN,NaN
18,f3f12fc90564a9b036680a887cd64668,817f85dbb65aa3e70831d90fe75cdf89,2016-10-04 13:15:52,NaT,NaN,NaN
19,5b1376fe61863fe3508011db309e35fe,440dd6ab244315c632130ecfb63827b1,2016-10-04 13:16:57,NaT,NaN,NaN